filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log
    multiline.pattern: "^[[:space:]]"
    multiline.negate: false
    multiline.match: after

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  setup.ilm.enabled: false

setup.template:
  name: "filebeat"
  patterns: ["filebeat-*"]
